name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *"   # ogni 12 ore
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate snake
        uses: Platane/snk@v3
        with:
          github_user_name: fcorbelli
          outputs: |
            dist/snake.svg
            dist/snake-dark.svg?palette=github-dark

      - name: Deploy to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
